name: DocBox

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the local repository
        uses: actions/checkout@v2

#       github.com/Ortus-Solutions/commandbox-action
      - name: Generate docs
        uses: Ortus-Solutions/commandbox-action@v1.0.6
        with:
          cmd: docbox generate mapping=demoApp excludes=testbox|coldbox|modules|tests strategy-outputDir=docs strategy-projectTitle='DocBox Demo App'

      - name: Commit Docs to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📘 DOC: Auto-generate DocBox API docs"